---
- hosts: all
  vars_files:
  - env_variables
  tasks:
  - name: Creating a repository file for Kubernetes
    become: true
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file.
    become: true
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Installing Docker 
    become: true
    shell: |
     yum install -y yum-utils device-mapper-persistent-data lvm2
     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     yum install docker-ce -y

  - name: Installing required packages
    become: true
    yum:
     name: "{{ item }}"
     state: present
    with_items: "{{ packages }}"

  - name: Starting and Enabling the required services
    become: true
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

  - name: Enabling Bridge Firewall Rule in /etc/sysctl.conf
    become: true
    shell: "echo 'net.bridge.bridge-nf-call-iptables=1' >> /etc/sysctl.conf"

  - name: Set local port range 1024 65535 in /etc/sysctl.conf
    become: true
    shell: "echo 'net.ipv4.ip_local_port_range = 1024 65535' >> /etc/sysctl.conf"
 
  - name: Set file-max 5000000 in /etc/sysctl.conf
    become: true
    shell: "echo 'fs.file-max = 5000000' >> /etc/sysctl.conf"
 
  - name: Set somaxconn 500 in /etc/sysctl.conf
    become: true
    shell: "echo 'net.core.somaxconn = 500' >> /etc/sysctl.conf"
 
  - name: Set * soft nproc 65535 in /etc/security/limits.conf
    become: true
    shell: "echo '* soft nproc 65535' >> /etc/security/limits.conf"

  - name: Set * hard nproc 65535 in /etc/security/limits.conf
    become: true
    shell: "echo '* hard nproc 65535' >> /etc/security/limits.conf"

  - name: Set * soft nofile 65535 in /etc/security/limits.conf
    become: true
    shell: "echo '* soft nofile 65535' >> /etc/security/limits.conf"

  - name: Set * hard nofile 65535 in /etc/security/limits.conf
    become: true
    shell: "echo '* hard nofile 65535' >> /etc/security/limits.conf"
    
  - name: Reboot nodes
    become: true
    reboot:

